-- MySQL Script generated by MySQL Workbench
-- Mi 27 Apr 2022 13:06:21 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema enlace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enlace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enlace` ;
USE `enlace` ;

-- -----------------------------------------------------
-- Table `enlace`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enlace`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `imagem_url` VARCHAR(255) NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `enlace`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enlace`.`temas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(20) NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enlace`.`postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enlace`.`postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NOT NULL,
  `abracei` INT NULL DEFAULT 0,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tema_id` BIGINT NULL,
  `usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `tema_id_idx` (`tema_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `enlace`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tema_id`
    FOREIGN KEY (`tema_id`)
    REFERENCES `enlace`.`temas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
