-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 11:48:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_enlace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_enlace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_enlace` DEFAULT CHARACTER SET utf8 ;
USE `db_enlace` ;

-- -----------------------------------------------------
-- Table `db_enlace`.`TB_TEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_enlace`.`TB_TEMA` (
  `tem_id` BIGINT NOT NULL AUTO_INCREMENT,
  `tem_nome` VARCHAR(45) NULL,
  `tem_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`tem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_enlace`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_enlace`.`TB_USUARIO` (
  `use_id` BIGINT NOT NULL,
  `use_nome` VARCHAR(45) NOT NULL,
  `use_email` VARCHAR(45) NOT NULL,
  `use_senha` VARCHAR(45) NOT NULL,
  `use_imagem_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`use_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_enlace`.`TB_POSTAGENS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_enlace`.`TB_POSTAGENS` (
  `pos_id` INT NOT NULL AUTO_INCREMENT,
  `fk_tem_id` BIGINT NOT NULL,
  `fk_use_id` BIGINT NOT NULL,
  `pos_conteudo` TEXT NOT NULL,
  `pos_titulo` VARCHAR(45) NOT NULL,
  `pos_abracei` BIGINT NOT NULL,
  `pos_criado_em` TIMESTAMP NOT NULL,
  `pos_atualizado_em` TIMESTAMP NOT NULL,
  PRIMARY KEY (`pos_id`),
  INDEX `use_id_idx` (`fk_use_id` ASC) ,
  INDEX `tem_id_idx` (`fk_tem_id` ASC) ,
  CONSTRAINT `use_id`
    FOREIGN KEY (`fk_use_id`)
    REFERENCES `db_enlace`.`TB_USUARIO` (`use_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tem_id`
    FOREIGN KEY (`fk_tem_id`)
    REFERENCES `db_enlace`.`TB_TEMA` (`tem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SELECT * 
FROM TB_POSTAGENS;

SELECT * 
FROM TB_USUARIO;

SELECT * 
FROM TB_TEMA;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
